//GENERALES
export const INICIANDO_CONSULTA = 'INICIANDO_CONSULTA';
export const FINALIZANDO_CONSULTA = 'FINALIZANDO_CONSULTA';

export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";
export const OBTENER_USUARIO = "OBTENER_USUARIO";

export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";

export const REGISTRO_ERROR = "REGISTRO_ERROR";
